# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "296d31e9b9528aa279b5b46b0628980f"
name = "bww-discounts"
handle = "bww-discounts"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "miniscript-discounts-functions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
